export const character = async () => [
  {
    isAlive: true,
    message: "You're all to die!",
    name: 'Joffrey',
    family: 'Baratheon',
    age: 18,
    kingdomYears: 1,
    type: 'king',
  },
  {
    isAlive: true,
    message: 'I hit first and ask later',
    name: 'Jamie',
    family: 'Lannister',
    age: 33,
    weapon: 'sword',
    skillsRange: 10,
    type: 'fighter',
  },
  {
    isAlive: true,
    message: 'I hit first and ask later',
    name: 'Daenerys',
    family: 'Targaryen',
    age: 18,
    weapon: 'dragons',
    skillsRange: 8,
    type: 'fighter',
  },
  {
    isAlive: true,
    message: 'I dunno know why, but I believe I am gonna die soon',
    name: 'Tyrion',
    family: 'Lannister',
    age: 40,
    lord: {
      isAlive: true,
      message: 'I hit first and ask later',
      name: 'Daenerys',
      family: 'Targaryen',
      age: 18,
      weapon: 'dragons',
      skillsRange: 8,
    },
    type: 'counselor',
  },
  {
    isAlive: true,
    message: 'I am a real loser',
    name: 'Bronn',
    family: 'Nieve',
    age: 35,
    serverRange: 5,
    master: {
      isAlive: true,
      message: 'I hit first and ask later',
      name: 'Jamie',
      family: 'Lannister',
      age: 33,
      weapon: 'sword',
      skillsRange: 10,
    },
    type: 'squire',
  },
];
